### ISSUE TITLE
Change morphology model input format

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-cat#151]
This is a reminder issue that I'm assigning to myself.

I'd like to change the morphology model input format a little, pretty much to what I did for spectra here: #119

So this:
```
pos:
  glon: {val: 332.391d, err: 0.014d}
  glat: {val: 0.138d, err: 0.013d}

morph:
  type: gauss
  sigma: {val: 0.136d, err: 0.008d}
```
would change to this:
```
morph:
  model:
    type: gauss
    parameters:
      glon: {val: 332.391d, err: 0.014d}
      glat: {val: 0.138d, err: 0.013d}
      sigma: {val: 0.136d, err: 0.008d}
  # could have other info about the measurement here
```
This requires an hour or two of tedious input data reformatting, but also changes to the spec, scripts, possibly output format and Gammapy, so I'd like to do it myself.
