### ISSUE TITLE
Improve pl2 spectrum input format

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-cat#47]
Currently this is our SED spec:

https://github.com/gammapy/gamma-cat/blob/5a7e774f77e93d334bf047fda81d2c6da09c2b8e/input/schemas/paper_source_info.schema.yaml#L101

We have ~ 20 spectra of type "PL2":
https://github.com/gammapy/gamma-cat/search?utf8=%E2%9C%93&q=pl2&type=Code

We're using the same parameter "norm" for differential and integral fluxes in the input files.
The documentation says this:
```
      norm:
        type: object
        additionalProperties: false
        unit: 1e-12 cm-2 s-1 TeV-1
        description: Flux norm parameter
```
So that's OK for "PL" differential spectra.

But for "PL2" integral spectral parameters, it's not documented what it should be.
@adonath told me it should be in `1e-12 cm-2 s-1`.
But that's error prone on data entry if it's not even documented in the schema.

---

This is a reminder issue for me to fix this.
It'll require some thought / discussion and a week or two of work.
Assigning to me for now, but help welcome of course!

It will probably involve a large change of model input format for `gamma-cat` and also in Gammapy,  e.g. adoption of the Fermi-LAT model XML serialisation format (or rather a YAML equivalent), or storing units in all the input files.

Since Astropy 1.3 one can pass strings to `Quantity`, so we could also change the pipeline to require units in the input files and parse those.
